### ISSUE TITLE
add request permission
on app boot

### ISSUE THREAD

**Issue by Hunter9888x** [rockon999/LeanbackLauncher#10]
Add Request all permission on app boot

Requests at once all declared permissions when the app starts.

On my fire tv won't allow me
To give storage permission

I select storage manually
To allow access to storage
In app settings nothing happens

**Comment by brandoningli** [comment]
I haven't explicitly granted a storage permission to LeanbackLauncher on my Fire TV Stick 2nd gen and it has worked just fine (Fire OS 5.2.6.9).

Could you elaborate a little more on the issue you're seeing, and what specific device/Fire OSversion you're using?

**Comment by Hunter9888x** [comment]
I try enabling storage permission
On my fire tv nothing happens

**Comment by brandoningli** [comment]
You're still not answering the question. Which fire tv device? What version of the OS? Is it working fine without you granting the storage permission?

**Comment by Hunter9888x** [comment]
Yes it is working fine

But app won't show up on
Launch on boot app

Without storage permission

**Comment by Hunter9888x** [comment]
Launch on boot
https://github.com/ITVlab/Launch-On-Boot

**Comment by brandoningli** [comment]
It's not an issue with this app, then. It's an issue with Launch-On-Boot not detecting apps that do not have the storage permission enabled. That shouldn't affect another app from detecting LeanbackLauncher anyway. Please file an issue over there and close this one.
